### ISSUE TITLE
Mongoose: Remove hook not triggered when removing 

### ISSUE THREAD

**Issue by Swissbite** [jspears/mers#40]
The remove hook will not be triggered while call Schema#findAndRemove.

This is a known circumstance by mongoose https://github.com/learnboost/mongoose/issues/1241 and marked as not a bug.

The easiest way would be to call find in routes.js and then remove in the callback.

See also http://mongoosejs.com/docs/api.html#model_Model.findOneAndRemove

**Comment by jspears** [comment]
Sorry for not merging this. I think this is now handled correctly.

I need a test to check events working properly.
