### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by starquake** [jspears/mers#44]
Am I allowed to use this in a commercial product?

**Comment by jspears** [comment]
Sure can.  I should add a license, any preference?  Otherwise I'll go with MIT.

**Comment by starquake** [comment]
MIT sounds great! And of course I will be contributing back!

**Comment by jspears** [comment]
I put a license in the develop branch, planning on pushing to master
shortly and doing a new npm release, soon after.
-Justin

**Comment by jspears** [comment]
added a license.
