### ISSUE TITLE
Custom ResultStream issue

### ISSUE THREAD

**Issue by ambrumyan** [jspears/mers#45]
When I am trying to add new method to Schema

DepartmentSchema.methods.superDo = function DepartmentSchema$hello(data){
   return Department.find({
       _id:this._id
   });
}

getting such error 

{"status":1,"error":"Cast to ObjectId failed for value \"superDo\" at path \"_id\""}

URL is  ->  /department//superDo 

When I am trying to do for instance like this

 /department/550ad5972aa071895a364180/superDo

Works perfect

**Comment by jspears** [comment]
you want to use a static function, if you need to access a function without an id.   but the method you have uses this._id so you will need to pass in an id.

```js

DepartmentSchema.statics.superDo = function DepartmentSchema$hello(query$id){
return Department.find({
_id:query$id
});
}

```
The behaviour is expected though the message is less than obvious

**Comment by ambrumyan** [comment]
Well It doesn't solves my problem, I am trying to create custom routes for post requests, if I will use statics I will need to add "finder" to the URL , is there any other way to do that without statics?

**Comment by jspears** [comment]
You
