### ISSUE TITLE
How do you use transformers ?

### ISSUE THREAD

**Issue by windmaomao** [jspears/mers#46]
I tried

    app.use('/api/v1', mers({uri:'mongodb://localhost/database'}).rest({
        mongoose:mongoose,
        transformers: {
            renameid: function (obj) {
                obj.id = obj._id;
                delete obj._id;
                return obj;
            }
        }
    }));

but i always getting the error "could not find transformer for renameid", how do I register a transformer ?

Fang

**Comment by jspears** [comment]
That's correct, there is a bug.  Fixed in the develop branch. I'll publish a new module tonight with any luck.
